### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by zdolny** [adamlm000/test#1]
Nie wiem, czy sprawdzales, ale obecnie strona nie dziala, jak powinna. Dokonalem paru zmian w branchu master i paru zmian w utworzonym przeze mnie branchu test.

Sprobuj wykonac nastepujace rzeczy:
- [ ] zaciagnij sobie zmiany do swojego lokalnego repozytorium
- [ ] domerguj brancha `test` do brancha `master`
- [ ] wypushuj zmiany w branchu master do zdalnego repozyturium
